name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ chore/pr-workflow ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps (ci)
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build

